# Generated by Django 5.2.6 on 2026-05-31 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0018_alter_product_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('umumiy', 'Umumiy'), ('elektrik', 'Elektrik'), ('avto_bezak', 'Avto bezak'), ('mator', 'Mator'), ('xadavoy', 'Xadavoy'), ('kuzuf', 'Kuzuf'), ('moy', 'Moy')], default='umumiy', max_length=20),
        ),
    ]
