# Generated by Django 5.2.6 on 2026-06-01 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0019_alter_product_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('hammasi', 'Hammasi'), ('elektrikjan', 'Elektrikjan'), ('avto_bezak', 'Avto Bezak'), ('mator_xadavoy', 'Mator Xadavoy'), ('chexol_polik', 'Chexol Polik'), ('moy_antifriz', 'Moy Antifriz')], default='umumiy', max_length=20),
        ),
    ]
